/**
 * Source of `~/.nakiros/ingest/hook-stop.cjs` — the tiny CommonJS script
 * Claude Code invokes from its Stop hook. Kept self-contained (no `require`
 * outside `node:*` builtins) so it has no install-time dependency surface
 * and runs in <50ms even on cold node starts.
 *
 * Contract with Claude Code: stdin receives a JSON payload with at least
 * `{ session_id, transcript_path, cwd, hook_event_name }`. We append it to
 * `~/.nakiros/ingest/queue/` for the daemon to drain — we do NOT import
 * anything from the daemon process so the user can disable Nakiros and the
 * hook still exits cleanly (queue files just pile up, drained on next start).
 *
 * The `.cjs` extension forces CommonJS interpretation regardless of any
 * sibling `package.json` (there is none in `~/.nakiros/`, but defensive).
 */
export const HOOK_STOP_SCRIPT_SOURCE = `#!/usr/bin/env node
// AUTO-GENERATED by Nakiros conversation-ingest. Do not edit by hand —
// regenerated every time you re-enable the ingest pipeline from the UI.

const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');

let raw = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => { raw += chunk; });
process.stdin.on('end', () => {
  let payload;
  try {
    payload = JSON.parse(raw);
  } catch {
    return;
  }
  if (!payload || typeof payload !== 'object') return;

  const queueDir = path.join(os.homedir(), '.nakiros', 'ingest', 'queue');
  try {
    fs.mkdirSync(queueDir, { recursive: true });
  } catch {
    return;
  }

  const ts = Date.now();
  const rawId = typeof payload.session_id === 'string' ? payload.session_id : 'unknown';
  const safeId = rawId.replace(/[^a-zA-Z0-9_-]/g, '');
  const filename = ts + '-' + safeId + '.json';
  const tmp = path.join(queueDir, filename + '.tmp');
  const finalPath = path.join(queueDir, filename);

  try {
    fs.writeFileSync(tmp, JSON.stringify({ ts: ts, payload: payload }), 'utf8');
    fs.renameSync(tmp, finalPath);
  } catch {
    // Silent — Claude Code waits on hook exit; never throw out of the script.
  }
});

process.stdin.on('error', () => {
  // Ignore — exit cleanly so Claude Code doesn't block on the hook.
});
`;
