/**
 * Sources of the two CJS hook scripts that Nakiros installs when the user
 * enables drift detection hooks:
 *
 *   - `~/.nakiros/drift/hook-stop.cjs`         — Stop hook
 *   - `~/.nakiros/drift/hook-userpromptsubmit.cjs` — UserPromptSubmit hook
 *
 * Both scripts are self-contained CommonJS (no external dependencies, only
 * `node:*` builtins) so they run in < 100ms on cold node starts and survive
 * daemon restarts gracefully.
 *
 * The `.cjs` extension forces CommonJS interpretation regardless of any
 * sibling `package.json` — `~/.nakiros/` has none, but this is defensive.
 *
 * Protocol:
 *  - Read JSON payload from stdin (Claude Code populates it for hook events).
 *  - Call `GET http://localhost:4242/api/drift?session=<id>` via `node:http`.
 *  - If the daemon is unreachable / returns an error / session absent: exit 0
 *    with no output — never break the conversation.
 *  - Env overrides (debug): `NAKIROS_DAEMON_URL`, `NAKIROS_DRIFT_FORCE`.
 *
 * We use `node:http` instead of `fetch` for maximum compatibility with Node
 * 18+ (fetch is available from Node 18 but http keeps us safe regardless).
 */

/** Source of `~/.nakiros/drift/hook-stop.cjs`. */
export const HOOK_STOP_SCRIPT_SOURCE = `#!/usr/bin/env node
// AUTO-GENERATED by Nakiros drift-hook installer. Do not edit by hand —
// regenerated every time you re-enable drift hooks from the Settings panel.

'use strict';

const http = require('node:http');
const https = require('node:https');
const os = require('node:os');

const TIMEOUT_MS = 2000;
const DAEMON_URL = process.env.NAKIROS_DAEMON_URL || 'http://localhost:4242';
const FORCE = process.env.NAKIROS_DRIFT_FORCE || '';

let raw = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', function(chunk) { raw += chunk; });
process.stdin.on('error', function() { process.exit(0); });
process.stdin.on('end', function() {
  var input;
  try {
    input = JSON.parse(raw);
  } catch (e) {
    process.exit(0);
    return;
  }
  if (!input || typeof input !== 'object') { process.exit(0); return; }

  // Avoid re-firing when Claude is continuing from a previous Stop hook.
  if (input.stop_hook_active === true) { process.exit(0); return; }

  var sessionId = input.session_id;
  if (!sessionId || typeof sessionId !== 'string') { process.exit(0); return; }

  var urlStr = DAEMON_URL + '/api/drift?session=' + encodeURIComponent(sessionId);
  if (FORCE) urlStr += '&force=' + encodeURIComponent(FORCE);

  var parsed;
  try {
    parsed = new URL(urlStr);
  } catch (e) {
    process.exit(0);
    return;
  }

  var mod = parsed.protocol === 'https:' ? https : http;
  var done = false;

  var req = mod.get({ hostname: parsed.hostname, port: parsed.port, path: parsed.pathname + parsed.search, timeout: TIMEOUT_MS }, function(res) {
    var body = '';
    res.setEncoding('utf8');
    res.on('data', function(d) { body += d; });
    res.on('end', function() {
      if (done) return;
      done = true;
      if (res.statusCode !== 200) { process.exit(0); return; }
      var data;
      try { data = JSON.parse(body); } catch (e) { process.exit(0); return; }
      var drift = data && data.drift;
      if (!drift) { process.exit(0); return; }
      var message = (drift.message || '') + ' ' + (drift.suggestion || '');
      var banner = 'Nakiros \\u2014 ' + message.trim();
      process.stdout.write(JSON.stringify({ systemMessage: banner }));
      process.exit(0);
    });
  });

  req.on('timeout', function() {
    if (!done) { done = true; req.destroy(); process.exit(0); }
  });
  req.on('error', function() {
    if (!done) { done = true; process.exit(0); }
  });
});
`;

/** Source of `~/.nakiros/drift/hook-userpromptsubmit.cjs`. */
export const HOOK_USER_PROMPT_SUBMIT_SCRIPT_SOURCE = `#!/usr/bin/env node
// AUTO-GENERATED by Nakiros drift-hook installer. Do not edit by hand —
// regenerated every time you re-enable drift hooks from the Settings panel.

'use strict';

const http = require('node:http');
const https = require('node:https');

const TIMEOUT_MS = 2000;
const DAEMON_URL = process.env.NAKIROS_DAEMON_URL || 'http://localhost:4242';
const FORCE = process.env.NAKIROS_DRIFT_FORCE || '';

let raw = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', function(chunk) { raw += chunk; });
process.stdin.on('error', function() { process.exit(0); });
process.stdin.on('end', function() {
  var input;
  try {
    input = JSON.parse(raw);
  } catch (e) {
    process.exit(0);
    return;
  }
  if (!input || typeof input !== 'object') { process.exit(0); return; }

  var sessionId = input.session_id;
  if (!sessionId || typeof sessionId !== 'string') { process.exit(0); return; }

  var urlStr = DAEMON_URL + '/api/drift?session=' + encodeURIComponent(sessionId);
  if (FORCE) urlStr += '&force=' + encodeURIComponent(FORCE);

  var parsed;
  try {
    parsed = new URL(urlStr);
  } catch (e) {
    process.exit(0);
    return;
  }

  var mod = parsed.protocol === 'https:' ? https : http;
  var done = false;

  var req = mod.get({ hostname: parsed.hostname, port: parsed.port, path: parsed.pathname + parsed.search, timeout: TIMEOUT_MS }, function(res) {
    var body = '';
    res.setEncoding('utf8');
    res.on('data', function(d) { body += d; });
    res.on('end', function() {
      if (done) return;
      done = true;
      if (res.statusCode !== 200) { process.exit(0); return; }
      var data;
      try { data = JSON.parse(body); } catch (e) { process.exit(0); return; }
      var drift = data && data.drift;
      if (!drift) { process.exit(0); return; }
      var additionalContext = [
        '[Nakiros drift detector] type=' + drift.type + ' severity=' + drift.severity,
        'Message au user : ' + (drift.message || ''),
        'Suggestion : ' + (drift.suggestion || ''),
        'Evidence : ' + JSON.stringify(drift.evidence || {}),
        'Note : un encart vient d\\'etre affiche au user via systemMessage. Adapte ton prochain tour : rappelle la suggestion si pertinent, propose un /clear ou une nouvelle session.',
      ].join('\\n');
      var out = {
        hookSpecificOutput: {
          hookEventName: 'UserPromptSubmit',
          additionalContext: additionalContext,
        },
      };
      process.stdout.write(JSON.stringify(out));
      process.exit(0);
    });
  });

  req.on('timeout', function() {
    if (!done) { done = true; req.destroy(); process.exit(0); }
  });
  req.on('error', function() {
    if (!done) { done = true; process.exit(0); }
  });
});
`;
